services:
  gtmotive.estimate.microservice.host:
    image: ${DOCKER_REGISTRY-}gtmotiveestimatemicroservicehost
    build:
      context: .
      dockerfile: GtMotive.Estimate.Microservice.Host/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MongoDb__ConnectionString=mongodb://mongodb:27017
      - MongoDb__DatabaseName=EstimateDb
    depends_on:
      - mongodb
    networks:
      - estimate-network

  mongodb:
    image: mongo:7.0
    container_name: estimate-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=EstimateDb
    restart: always
    volumes:
      - mongodb-data:/data/db
    networks:
      - estimate-network

volumes:
  mongodb-data:
    driver: local

networks:
  estimate-network:
    driver: bridge
